version: "2.4"
services:
  # realm:
  #   build: ./realm
  #   environment:
  #       - REALM_APPID
  #   depends_on:
  #       - mqtt      
  mosquitto-mqtt:
    image: "eclipse-mosquitto"
    volumes:
        - ./mosquitto-mqtt/:/mosquitto/config/
    ports:
        - "1883:1883"
